#include "Player.h"

#include <algorithm>

#include "Game/Components/Respawn.h"
#include "whalECS/src/ECS.h"

#include "Settings.h"
#include "Systems/System.h"
#include "Util/MathUtil.h"
#include "Util/Print.h"

#include "ECS/AnimUtil.h"
#include "ECS/Animator.h"
#include "ECS/Collision.h"
#include "ECS/Draw.h"
#include "ECS/Entities/Camera.h"
#include "ECS/Name.h"
#include "ECS/PlayerControl.h"
#include "ECS/RigidBody.h"
#include "ECS/Systems/Physics.h"
#include "ECS/Systems/TagTrackers.h"
#include "ECS/Tags.h"
#include "ECS/Transform.h"
#include "ECS/Velocity.h"

namespace whal {

// RESEARCH this could be simplified. Ideally this should be read from a file generated by aseprite?
// OR i can generate when the texture atlas is compiled -- but I'm not sure how to get the IDs in there
// File would look something like this:
// "basename","count", "secondsPerFile"
// "actor/player-run","4", "0.25"
// "actor/player-idle", "2", "1.0"
//
// this way, the only thing stored in code is animation names. Changing # of frames and file names is trivial
//
// per-frame duration could also be interesting, for a key-frame-like effect

namespace PlayerAnim {

enum AnimId : s32 { IDLE, RUN, JUMP, RISE, PEAK, FALL, JUMP_FORWARD, RISE_FORWARD, PEAK_FORWARD, FALL_FORWARD };

static const AnimInfo S_PLAYER_ANIM_INFO = {
    {"actor/witch-idle", PlayerAnim::IDLE, 5, 0.33},
    {"actor/witch-run", PlayerAnim::RUN, 8, 0.1},
    {"actor/witch-jumpforward", PlayerAnim::JUMP_FORWARD, 2, 0.1},
    {"actor/witch-jumpforward_rising", PlayerAnim::RISE_FORWARD, 4, 0.1},
    {"actor/witch-jumpforward_peak", PlayerAnim::PEAK_FORWARD, 2, 0.1},
    {"actor/witch-fall", PlayerAnim::FALL_FORWARD, 4, 0.1},
    {"actor/player-jump", PlayerAnim::JUMP, 1, 1.0},  // TODO
    {"actor/player-fall", PlayerAnim::FALL, 1, 1.0},  // TODO
};

bool brain(Animator& animator, ecs::Entity entity) {
    auto rbOpt = entity.tryGet<RigidBody>();
    RigidBody rb;
    if (rbOpt) {
        rb = *rbOpt.value();
    }

    auto jumperOpt = entity.tryGet<Jumper>();

    auto& vel = entity.get<Velocity>();
    auto& sprite = entity.get<Sprite>();

    f32 unsquishStep = System::dt() * 1.50;
    sprite.scale = {approach(sprite.scale.x(), 1.0, unsquishStep), approach(sprite.scale.y(), 1.0, unsquishStep)};
    if (rb.isGrounded) {
        if (rb.isLanding) {
            f32 squish = std::min(abs(vel.total.y()) / abs(TERMINAL_VELOCITY_Y), 1.0f);
            sprite.scale = {myLerp(1, 1.25, squish), myLerp(1, 0.8, squish)};
            System::audio.playClip(Sfx::LAND, 0.0375 * squish);
        }
        if (vel.total.x() != 0) {
            if (animator.setAnimation(RUN)) {
                System::audio.playClip(Sfx::FOOTSTEPTEST, 0.075);
                return true;
            }
        } else {
            if (animator.setAnimation(IDLE)) {
                return true;
            }
        }
    } else {
        if (jumperOpt && jumperOpt.value()->isJumping) {
            if ((animator.getAnimation().id == JUMP_FORWARD || animator.getAnimation().id == RISE_FORWARD) && vel.total.y() <= 1 &&
                animator.setAnimation(PEAK_FORWARD)) {
                return true;
            }
            // TODO once implemented
            // if (animator.getAnimation().id == JUMP && vel.total.y() <= 1 && animator.setAnimation(PEAK)) {
            //     return true;
            // }

            bool isJumping = [](s32 animId) -> bool {
                switch (animId) {
                case JUMP:
                case JUMP_FORWARD:
                case RISE:
                case RISE_FORWARD:
                case PEAK:
                case PEAK_FORWARD:
                    return true;
                default:
                    return false;
                }
                return false;
            }(animator.getAnimation().id);

            // TODO normal jump
            if (!isJumping && animator.setAnimation(JUMP_FORWARD)) {
                sprite.scale = {0.8, 1.25};
                System::audio.playClip(Sfx::JUMP, 0.35);
                return true;
            }
        } else {
            // falling, switch to peak or fall anim depending on current state
            switch (animator.getAnimation().id) {
            case IDLE:
                return animator.setAnimation(FALL_FORWARD);  // TODO check xVel
            case RUN:
                return animator.setAnimation(FALL_FORWARD);
            case FALL:
                break;
            case FALL_FORWARD:
                break;
            case RISE:
            case JUMP:
                return animator.setAnimation(PEAK);
            case RISE_FORWARD:
            case JUMP_FORWARD:
                return animator.setAnimation(PEAK_FORWARD);
            case PEAK:
                break;  // handled below
            case PEAK_FORWARD:
                break;  // handled below
            }
        }
    }

    // animation did not change
    bool frameChanged = basicAnimation(animator, entity);
    bool animEnded = frameChanged && animator.curFrameIx == 0;
    if (frameChanged && animator.getAnimation().id == RUN && animator.curFrameIx % 2 == 1) {
        System::audio.playClip(Sfx::FOOTSTEPTEST, 0.05);
    }

    // do tween transitions
    if (animEnded) {
        switch (animator.getAnimation().id) {
        case PEAK_FORWARD:
            return animator.setAnimation(FALL_FORWARD);
        case PEAK:
            return animator.setAnimation(FALL);
        case JUMP_FORWARD:
            return animator.setAnimation(RISE_FORWARD);
        case JUMP:
            return animator.setAnimation(RISE);
        default:
            break;
        }
    }

    return frameChanged;
}

}  // namespace PlayerAnim

Expected<ecs::Entity> createPlayerWithSprite(Sprite sprite) {
    auto expected = System::ecs->entity(false);
    if (!expected.isExpected()) {
        return expected;
    }
    auto player = expected.value();
    auto _ = ecs::DeferActivate(player);

    Transform2D transform = Transform2D::tiles(15, 10);  // TODO get the last level the player was in and spawn in the start point -- or maybe have
                                                         // some SafeLocatoinCheckpoint triggers in the map data
    player.add(transform);
    player.add(Name("Player"));
    player.add<Player>();
    player.add<Velocity>();
    player.add<PlayerControl>();
    player.add<Jumper>();

    if (!getCamera()) {
        createCamera(player);
    }

    // graphics
    Animator animator;
    loadAnimations(animator, PlayerAnim::S_PLAYER_ANIM_INFO);
    animator.brain = &PlayerAnim::brain;
    player.add(animator);

    Frame frame = animator.getFrame();
    sprite.depth = Depth::Player;
    sprite.setFrameSize(frame.dimensionsTexels.x(), frame.dimensionsTexels.y());
    sprite.atlasPositionTexels = frame.atlasPositionTexels;
    player.add(sprite);

    constexpr s32 width = 16;
    // constexpr s32 height = 16;
    constexpr s32 halfLenX = PIXELS_PER_TEXEL * width / 4;
    constexpr s32 halfLenY = PIXELS_PER_TEXEL * 6;
    player.add(ActorCollider(transform, Vector2i(halfLenX, halfLenY)));
    player.add<RigidBody>();
    // player.add<FreeControl>();

    player.add(Respawn{2, &respawnPlayer,
                       []() {
                           System::audio.playClip(Sfx::DEATH);
                           System::audio.setMusicVolume(0.75);
                           System::audio.setFilterMusic(AudioPlayer::Filter::LowPass);
                       },
                       []() {
                           System::audio.setMusicVolume(1);
                           System::audio.setFilterMusic(AudioPlayer::Filter::None);
                       }});

    return player;
}

Expected<ecs::Entity> createPlayer() {
    Sprite sprite;
    return createPlayerWithSprite(sprite);
}

// use sprite with pre-constructed vao/vbo created on main thread
void respawnPlayer(Sprite sprite) {
    Expected<ecs::Entity> player = createPlayerWithSprite(sprite);
    if (!player.isExpected()) {
        print(player.error());
    }
}

}  // namespace whal
