#include "Settings.h"

// WINDOW SIZES
s32 WINDOW_WIDTH_RENDER = 1280;
s32 WINDOW_HEIGHT_RENDER = 720;
s32 WINDOW_WIDTH_GAME = 320;
s32 WINDOW_HEIGHT_GAME = 180;

// DERIVED
f32 FWINDOW_WIDTH_RENDER = WINDOW_WIDTH_RENDER;
f32 FWINDOW_HEIGHT_RENDER = WINDOW_HEIGHT_RENDER;
f32 FWINDOW_WIDTH_GAME = WINDOW_WIDTH_GAME;
f32 FWINDOW_HEIGHT_GAME = WINDOW_HEIGHT_GAME;
f32 VIRTUAL_SCREEN_RATIO = FWINDOW_WIDTH_RENDER / FWINDOW_WIDTH_GAME;

// EXTERN
s32 GetRenderWidth() {
    return WINDOW_WIDTH_RENDER;
}

s32 GetRenderHeight() {
    return WINDOW_HEIGHT_RENDER;
}
