#include "Player.h"

#include "Components/Callback.h"
#include "Components/Light.h"
#include "Entities/Block.h"
#include "Entities/Particle.h"
#include "Game.h"
#include "Game/Components/Blaster.h"
#include "Game/Components/Respawn.h"
#include "Game/Save/EventFlags.h"
#include "whalECS/src/ECS.h"

#include "Settings.h"
#include "Sys/System.h"
#include "Util/MathUtil.h"
#include "Util/Print.h"

#include "Components/AnimUtil.h"
#include "Components/Animator.h"
#include "Components/Collision.h"
#include "Components/Draw.h"
#include "Components/Name.h"
#include "Components/PlayerControl.h"
#include "Components/RigidBody.h"
#include "Components/Tags.h"
#include "Components/Transform.h"
#include "Components/Velocity.h"
#include "Entities/Camera.h"
#include "Systems/Physics.h"
#include "Systems/TagTrackers.h"

using namespace whal;

// RESEARCH this could be simplified. Ideally this should be read from a file generated by aseprite?
// OR i can generate when the texture atlas is compiled -- but I'm not sure how to get the IDs in there
// File would look something like this:
// "basename","count", "secondsPerFile"
// "actor/player-run","4", "0.25"
// "actor/player-idle", "2", "1.0"
//
// this way, the only thing stored in code is animation names. Changing # of frames and file names is trivial
//
// per-frame duration could also be interesting, for a key-frame-like effect

namespace PlayerAnim {

enum AnimId : s32 { IDLE, RUN, JUMP, RISE, PEAK, FALL, JUMP_FORWARD, RISE_FORWARD, PEAK_FORWARD, FALL_FORWARD };

static const AnimInfo S_PLAYER_ANIM_INFO = {
    {"actor/witch-idle", PlayerAnim::IDLE, 5, 0.33},
    {"actor/witch-run", PlayerAnim::RUN, 8, 0.1},
    {"actor/witch-jumpforward", PlayerAnim::JUMP_FORWARD, 2, 0.1},
    {"actor/witch-jumpforward_rising", PlayerAnim::RISE_FORWARD, 4, 0.1},
    {"actor/witch-jumpforward_peak", PlayerAnim::PEAK_FORWARD, 2, 0.1},
    {"actor/witch-fall", PlayerAnim::FALL_FORWARD, 4, 0.1},
    {"actor/witch-jumpstill", PlayerAnim::JUMP, 3, 0.1},
    {"actor/witch-jumpstill_rising", PlayerAnim::RISE, 4, 0.1},
    {"actor/witch-jumpstill_peak", PlayerAnim::PEAK, 3, 0.1},
    {"actor/witch-fallstill", PlayerAnim::FALL, 4, 0.1},
};

bool brain(Animator& animator, ecs::Entity entity) {
    auto rbOpt = entity.tryGet<RigidBody>();
    RigidBody rb;
    if (rbOpt) {
        rb = *rbOpt;
    }

    auto jumperOpt = entity.tryGet<Jumper>();

    auto& vel = entity.get<Velocity>();
    auto& sprite = entity.get<Draw>().getSprite();

    f32 unsquishStep = System::dt() * 1.50;
    sprite.scale = {approach(sprite.scale.x, 1.0, unsquishStep), approach(sprite.scale.y, 1.0, unsquishStep)};
    if (rb.isGrounded) {
        if (rb.isLanding) {
            f32 squishAmount = std::min(abs(vel.total.y) / abs(TERMINAL_VELOCITY_Y), 1.0f);
            sprite.scale = {myLerp(1, 1.25, squishAmount), myLerp(1, 0.8, squishAmount)};
            System::audio.playClip(Sfx::LAND, 0.0375 * squishAmount);
            particleBurst(entity.get<Transform2D>(), Direction::N, rb.groundMaterial, 8 * squishAmount, Depth::Foreground1, 0.25);
        }
        if (vel.total.x != 0) {
            if (animator.setAnimation(RUN)) {
                System::audio.playClip(Sfx::FOOTSTEPTEST, 0.075);
                return true;
            }
        } else {
            if (animator.setAnimation(IDLE)) {
                return true;
            }
        }
    } else {
        if (jumperOpt && jumperOpt->isJumping) {
            bool isJumping = [](s32 animId) -> bool {
                switch (animId) {
                case JUMP:
                case JUMP_FORWARD:
                case RISE:
                case RISE_FORWARD:
                case PEAK:
                case PEAK_FORWARD:
                    return true;
                default:
                    return false;
                }
                return false;
            }(animator.getAnimation().id);

            const auto jumpType = abs(vel.total.x) < 0.1 ? JUMP : JUMP_FORWARD;
            if (!isJumping && animator.setAnimation(jumpType)) {
                sprite.scale = {0.8, 1.25};
                System::audio.playClip(Sfx::JUMP, 0.35);
                return true;
            }
        } else {
            // falling, switch to peak or fall anim depending on current state
            switch (animator.getAnimation().id) {
            case IDLE: {
                const auto fallType = abs(vel.total.x) < 0.1 ? FALL : FALL_FORWARD;
                return animator.setAnimation(fallType);
            }
            case RUN:
                return animator.setAnimation(FALL_FORWARD);
            case FALL:
                break;
            case FALL_FORWARD:
                break;
            case RISE:
            case JUMP:
                return animator.setAnimation(PEAK);
            case RISE_FORWARD:
            case JUMP_FORWARD:
                return animator.setAnimation(PEAK_FORWARD);
            case PEAK:
                break;  // handled below
            case PEAK_FORWARD:
                break;  // handled below
            }
        }
    }

    // animation did not change
    bool frameChanged = basicAnimation(animator, entity);
    bool animEnded = frameChanged && animator.curFrameIx == 0;
    if (frameChanged && animator.getAnimation().id == RUN && animator.curFrameIx % 2 == 1) {
        System::audio.playClip(Sfx::FOOTSTEPTEST, 0.05);
    }

    // do tween transitions
    if (animEnded) {
        switch (animator.getAnimation().id) {
        case PEAK_FORWARD:
            return animator.setAnimation(FALL_FORWARD);
        case PEAK:
            return animator.setAnimation(FALL);
        case JUMP_FORWARD:
            return animator.setAnimation(RISE_FORWARD);
        case JUMP:
            return animator.setAnimation(RISE);
        default:
            break;
        }
    }

    return frameChanged;
}

static Animator getAnimator() {
    Animator animator;
    loadAnimations(animator, PlayerAnim::S_PLAYER_ANIM_INFO);
    animator.brain = &PlayerAnim::brain;
    return animator;
}

}  // namespace PlayerAnim

void respawnPlayer(Transform2D transform);

Expected<ecs::Entity> createPlayerAt(Transform2D transform) {
    auto expected = System::world->entity(false);
    if (!expected.isExpected()) {
        return expected;
    }
    auto player = expected.value();
    auto _ = ecs::DeferActivate(player);

    player.add(transform);
    player.add(Name("Player"));
    player.add<Player>();
    player.add<Velocity>();
    player.add<PlayerControl>();
    player.add<Jumper>();
    player.add<Wiggle>();

    // if (true) {
    if (EventFlags::check(EventFlags::HasMagicHat)) {
        player.add<Blaster>();
    }

    // check what kind of camera the level we're in uses
    bool followPlayer = true;
    auto levelOpt = Game::instance().getScene().getLevelAt(transform.position);
    if (levelOpt) {
        auto activeLevel = Game::instance().getScene().getLoadedLevel(*levelOpt);
        if (activeLevel.isExpected() && !activeLevel.value()->cameraFollow) {
            followPlayer = false;
        }
    }

    if (followPlayer) {
        setCameraTarget(player);
    }

    // testing
    // DrawBezierQuad bezier(Vector2i(TEXELS_PER_TILE * 3, TEXELS_PER_TILE), Vector2i(TEXELS_PER_TILE * 3, 0), RED);
    // player.add(Draw(bezier));

    // DrawStraightLine line{8, RED, 1, Depth::Player, true};
    // player.add(Draw(line));
    // player.add(AngularVelocity::fromSecondsPerRotation(1));

    // graphics
    player.add(PlayerAnim::getAnimator());

    Frame frame = player.get<Animator>().getFrame();
    Sprite sprite(Depth::Player, frame);
    player.add(Draw(sprite));
    // player.add(Draw(sprite, TextureID::LayerGlow));
    // player.add(Draw(sprite, TextureID::LayerBloom));

    constexpr s32 width = 16;
    constexpr s32 halfLenX = PIXELS_PER_TEXEL * width / 4;
    constexpr s32 halfLenY = PIXELS_PER_TEXEL * 6;
    player.add(Collider::Actor(transform, Vector2i(halfLenX, halfLenY)));
    // player.add(ColliderOffset(Vector2i(8, 4)));
    // player.get<Collider>().setMaterial(WorldMaterial::Soft);
    // player.add(Collider::SemiSolid(transform, Vector2i(halfLenX, halfLenY)));
    // player.add(Collider::Solid(transform, Vector2i(halfLenX, halfLenY)));
    player.add<RigidBody>();
    // player.add<FreeControl>();
    // player.add(DrawText("Test message. This message is really long the quick fox jumped over the lazy dog", GRAY, {100, 100}, true));

    // player.add(PointLight{TEXELS_PER_TILE * 8, TEXELS_PER_TILE, WHITE});
    // player.add(BoxLight{{TEXELS_PER_TILE * 3, TEXELS_PER_TILE, {255, 255, 204, 255}}, frame.dimensionsTexels});
    // player.add(Radiance{TEXELS_PER_TILE * 1, TEXELS_PER_TILE, {255, 255, 255, 175}});
    player.add(ShadowLight{TEXELS_PER_TILE * 12, TEXELS_PER_TILE, WHITE});

    // player.add(ParticleEmitter(Color(7, 82, 250, 179), 0.25f, ParticleSetting::RigidBody | ParticleSetting::Light | ParticleSetting::RightOnly,
    // 150,
    //                            75, {8, 8}, {0, TEXELS_PER_TILE}));

    player.add(Respawn{2, &respawnPlayer, transform.position,
                       []() {
                           System::audio.playClip(Sfx::DEATH);
                           System::audio.setMusicVolume(0.75);
                           System::audio.setFilterMusic(AudioPlayer::Filter::LowPass);
                       },
                       []() {
                           System::audio.setMusicVolume(1);
                           System::audio.setFilterMusic(AudioPlayer::Filter::None);
                       }});
    player.add<IUseCheckpoints>();

    // orbit component testing:
    // auto eSprite = Sprite::fromPath("actor/magichat1");
    // if (eSprite.isExpected()) {
    //     auto decal = createDecal(transform, eSprite.value()).value();
    //     decal.add(Orbit(player, 3 * PIXELS_PER_TILE, 0.5, {0, 6}));
    // } else {
    //     print(eSprite.error());
    // }

    return player;
}

// for debugging
Expected<ecs::Entity> createPlayer() {
    Transform2D trans;
    if (Game::instance().getScene().isValid()) {
        trans = Transform2D(Game::instance().getScene().initialSpawnPoint);
    } else {
        trans = Transform2D::tiles(15, 10);
    }
    return createPlayerAt(trans);
}

void respawnPlayer(Transform2D trans) {
    Expected<ecs::Entity> player = createPlayerAt(trans);
    if (!player.isExpected()) {
        print(player.error());
    }
}
